# Generated by Django 4.2.16 on 2025-05-26 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='recommends',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
