# Generated by Django 4.2.21 on 2025-05-27 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_thread_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='read_date',
            new_name='reading_date',
        ),
    ]
