# Generated by Django 4.2.21 on 2025-05-27 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_read_date_thread_reading_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='create_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='thread',
            old_name='update_date',
            new_name='updated_at',
        ),
    ]
